# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: msbuild homuwitch-decryptor.sln /p:Configuration=Release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: homuwitch-decryptor-release
        path: |
           bin/Release/*
           !bin/Release/*.xml
           !bin/Release/*.pdb
           !bin/Release/*.config